name: "Media Library"
slug: "media-library"
description: "Media Library (games, movies, series)"
version: "1.3.1"
url: "https://github.com/NikolausStoll/media-library"

arch:
  - amd64
  - aarch64
  - armv7

startup: application
init: false

ingress: true
ingress_port: 8099

ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: "Media Library Web UI (direct)"

image: "ghcr.io/nikolausstoll/media-library"

options:
  port: 8099
  db_path: "/data/backend.db"
  static_dir: "/app/public"
  TMDB_API_KEY: ""
schema:
  port: int(1024,65535)
  db_path: str
  static_dir: str
  TMDB_API_KEY: password